version: 0.9.0.{build}

install:
  - ps: Install-Module psake -Scope CurrentUser -Force
  - ps: Install-Module VSSetup -Scope CurrentUser

skip_commits:
  files:
    - README.md

image: Visual Studio 2017

# FIXME: Enabled assembly info patching

build_script:
  - ps: Invoke-Psake build.ps1
  - ps: Get-ChildItem .

test: off

artifacts:
  - path: ./CBreeze/UncommonSense.CBreeze.Automation/Output

deploy: off