version: 0.9.0.{build}

init:
  - ps: Get-Module -Name Pester -ListAvailable
  - ps: Get-Module -Name psake -ListAvailable

skip_commits:
  files:
    - README.md

image: Visual Studio 2017

# FIXME: Enabled assembly info patching

configuration:
  - Debug

build: off

test: off 

artifacts: off

deploy: off