version: 0.9.0.{build}

install:
  - ps: Install-Module psake -Scope CurrentUser -Force
  - ps: Install-Module VSSetup -Scope CurrentUser -Force

skip_commits:
  files:
    - README.md

image: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  - ps: Invoke-Psake build.ps1
  
test: off

artifacts:
  - path: ./CBreeze/Output

deploy: off

on_finish:
  - ps: Get-ChildItem . -Recurse