version: 0.9.0.{build}

install:
  - ps: Install-Module psake -Scope CurrentUser -Force

skip_commits:
  files:
    - README.md

image: Visual Studio 2017

# FIXME: Enabled assembly info patching

configuration:
  - Debug

build: off

test: off 

artifacts: off

deploy: off