version: 0.9.0.{build}

install:
  - ps: Install-Module psake -Scope CurrentUser -Force
  - ps: Install-Module VSSetup -Scope CurrentUser -Force

skip_commits:
  files:
    - README.md

image: Visual Studio 2017

# FIXME: Enabled assembly info patching

build_script:
  - ps: Invoke-Psake build.ps1
  
test: off

artifacts:
  - path: ./CBreeze/Output
  - path: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating'

deploy: off